twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        img_path: '/images/'
        img_juegos_path: '/images/juegos/'
        img_icons_path: '/images/icons/'
        img_logo: '/images/logo.png'

when@test:
    twig:
        strict_variables: true
